### ISSUE TITLE
Issue when reloading "lxp" twice

### ISSUE THREAD

**Issue by lmika** [tomasguisasola/luaexpat#2]
When calling `require "lxp"` more than once, and forcing the second call to reload the module by, for example setting `packages.loaded["lxp"] = nil`, the returned value of subsequent calls after the first one is a boolean, instead of the lxp module table.

To recreate:

```
local l1 = require "lxp"
package.loaded["lxp"] = nil   -- Force a reload of the "lxp" module
local l2 = require "lxp"

assert(type(l1) == "table", "l1 is not a table")
assert(type(l2) == "table", "l2 is not a table")  -- This assertion will fail
```

This is using LuaJIT 2.1.0-beta3 along with OpenRestry 0.21 installed as part of Kong 1.0.0rc2.

I believe the problem relates to [line 581 of lxplib.c](https://github.com/tomasguisasola/luaexpat/blame/master/src/lxplib.c#L581) where the C loader function is returning nothing when the metatable is already in the registry.  I suspect that when this occurs, the `require` call is [performing this pathway](https://www.lua.org/manual/5.1/manual.html#pdf-require):

> If the loader returns no value and has not assigned any value to package.loaded[modname], then require assigns true to this entry

I can propose a PR to fix this if you are interested.

**Comment by jinwg** [comment]
@lmika ,  i use openresty 1.13.6.2 with LuaJIT 2.1.0-beta3,  but i always get nil when calling "require lxp",  but seem you don't have the problem,  which version are you using?

**Comment by lmika** [comment]
We're using OpenResty 0.21, but I believe we've declared "lxp" as a Lua rock dependency.  I'm not sure if OpenResy comes with "lxp" out of the box.

**Comment by jinwg** [comment]
I make the openresty working with luaRocks,  only have problem with lxp.   are you using Linux or MacOS?

**Comment by lmika** [comment]
This is on Linux, specifically AWS Linux 2017.2

**Comment by Tieske** [comment]
see https://github.com/lunarmodules/luaexpat/pull/8

**Comment by Tieske** [comment]
This can be closed now

**Comment by tomasguisasola** [comment]
This project is now substituted by lunarmodules/luaexpat
