### ISSUE TITLE
missing method getcurrentbytecount

### ISSUE THREAD

**Issue by fperrad** [tomasguisasola/luaexpat#3]
the release 1.3.0 (from matthewwild) adds a method `getcurrentbytecount`, see <http://matthewwild.co.uk/projects/luaexpat/index.html#history>

this method is now missing.

[prosody](https://prosody.im/doc/depends#luaexpat) warns about its lack.

```lua
-- from dependencies.lua

		if not lxp.new({}).getcurrentbytecount then
			prosody.log("error", "The version of LuaExpat on your system does not support "
				.."stanza size limits, which may leave servers on untrusted "
				.."networks (e.g. the internet) vulnerable to denial-of-service "
				.."attacks. You should upgrade to LuaExpat 1.3.0 or higher as "
				.."soon as possible. See "
				.."https://prosody.im/doc/depends#luaexpat for more information.");
		end
```

**Comment by fapsi** [comment]
Would it be possible to update the version on luarocks including the fix?
Thanks in advance and cheers!

**Comment by tomasguisasola** [comment]
Could you send me a test case?  I couldn't make it return anything but 0!

**Comment by fapsi** [comment]
EDIT: Ah found it in the doku. I will provide you a test case on upcoming weekend: https://github.com/libexpat/libexpat/blob/master/expat/doc/reference.html

> Return the number of bytes in the current event. Returns
<code>0</code> if the event is inside a reference to an internal
entity and for the end-tag event for empty element tags (the later can
be used to distinguish empty-element tags from empty elements using
separate start and end tags).

**Comment by tomasguisasola** [comment]
Hi

Thanks.  I'm waiting your contact.

Regards,
Tomás

Em qua, 10 de abr de 2019 às 14:24, fapsi <notifications@github.com>
escreveu:
